import json

notebook_path = "cbers4asat-rgbn-composite-test.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

source_lines = [
    "#Adaptado do tutorial https://cbers4asat.readthedocs.io/pt-br/latest/examples/#download-de-produtos por Gabriel Russo\n",
    "#Composição rgbn dinâmica para as imagens lidas da pasta C:/Users/xavie/cipc-data\n",
    "\n",
    "import os\n",
    "import glob\n",
    "from cbers4asat.tools import rgbn_composite\n",
    "import rasterio as rio\n",
    "from rasterio.plot import show\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "base_dir = 'C:/Users/xavie/cipc-data/raw'\n",
    "out_dir = 'C:/Users/xavie/cipc-data/stack'\n",
    "os.makedirs(out_dir, exist_ok=True)\n",
    "\n",
    "# Dicionário de mapeamento das bandas: WFI CBERS -> 13, 14, 15, 16. WFI Amazonia1 -> 1, 2, 3, 4\n",
    "band_mapping = {\n",
    "    'AMAZONIA-1': {'red': 'BAND3', 'green': 'BAND2', 'blue': 'BAND1', 'nir': 'BAND4'},\n",
    "    'CBERS-4A': {'red': 'BAND15', 'green': 'BAND14', 'blue': 'BAND13', 'nir': 'BAND16'},\n",
    "    'CBERS-4': {'red': 'BAND15', 'green': 'BAND14', 'blue': 'BAND13', 'nir': 'BAND16'}\n",
    "}\n",
    "\n",
    "processed_files = []\n",
    "scene_dirs = glob.glob(os.path.join(base_dir, '*'))\n",
    "\n",
    "# Vamos usar apenas a primeira cena encontrada de cada satelite\n",
    "sats_found = []\n",
    "\n",
    "for scene_dir in scene_dirs:\n",
    "    if not os.path.isdir(scene_dir):\n",
    "        continue\n",
    "        \n",
    "    if 'AMAZONIA1' in scene_dir:\n",
    "        sat_name = 'AMAZONIA-1'\n",
    "    elif 'CBERS4A' in scene_dir:\n",
    "        sat_name = 'CBERS-4A'\n",
    "    elif 'CBERS4_' in scene_dir:\n",
    "        sat_name = 'CBERS-4'\n",
    "    else:\n",
    "        continue\n",
    "        \n",
    "    if sat_name in sats_found:\n",
    "        continue  # já gerou para este satélite\n",
    "        \n",
    "    mapping = band_mapping[sat_name]\n",
    "    tifs = glob.glob(os.path.join(scene_dir, '*.tif'))\n",
    "    \n",
    "    bands_paths = {}\n",
    "    for color, band_suffix in mapping.items():\n",
    "        for t in tifs:\n",
    "            if t.endswith(f\"{band_suffix}.tif\"):\n",
    "                bands_paths[color] = t\n",
    "                break\n",
    "                \n",
    "    if len(bands_paths) == 4:\n",
    "        out_filename = f\"{sat_name}_TRUE_COLOR.tif\"\n",
    "        print(f\"Gerando composição para {sat_name}...\")\n",
    "        \n",
    "        # Substitui contrabarras por barras, útil no Windows\n",
    "        bands_paths = {k: v.replace('\\\\', '/') for k, v in bands_paths.items()}\n",
    "        \n",
    "        rgbn_composite(red=bands_paths['red'],\n",
    "                       green=bands_paths['green'],\n",
    "                       blue=bands_paths['blue'],\n",
    "                       nir=bands_paths['nir'],\n",
    "                       filename=out_filename,\n",
    "                       outdir=out_dir)\n",
    "        \n",
    "        processed_files.append((sat_name, os.path.join(out_dir, out_filename)))\n",
    "        sats_found.append(sat_name)\n",
    "\n",
    "if processed_files:\n",
    "    fig, ax = plt.subplots(1, len(processed_files), figsize=(6 * len(processed_files), 6))\n",
    "    if len(processed_files) == 1:\n",
    "        ax = [ax]\n",
    "        \n",
    "    for i, (sat_name, filepath) in enumerate(processed_files):\n",
    "        raster = rio.open(filepath)\n",
    "        # Normaliza a visualização caso a imagem seja 10-bit ou mais (opcional para exibição nítida)\n",
    "        show(raster.read((1,2,3)), transform=raster.transform, ax=ax[i], title=sat_name)\n",
    "        \n",
    "    plt.tight_layout()\n",
    "    plt.show()\n"
]

nb["cells"][0]["source"] = source_lines

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Notebook modified successfully.")
